//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAdministrationSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AptitudeQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AptitudeQuestion()
        {
            this.AptitudeAnswers = new HashSet<AptitudeAnswer>();
        }
    
        public int QueId { get; set; }
        public string Que { get; set; }
        public string QueOpA { get; set; }
        public string QueOpB { get; set; }
        public string QueOpC { get; set; }
        public string QueOpD { get; set; }
        public string QueAns { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AptitudeAnswer> AptitudeAnswers { get; set; }
    }
}
