//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAdministrationSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateInfo
    {
        public int CandidateId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SSC_Marks { get; set; }
        public string SSC_College { get; set; }
        public Nullable<int> SSC_PassingYear { get; set; }
        public Nullable<int> HSC_Marks { get; set; }
        public string HSC_College { get; set; }
        public Nullable<int> HSC_PassingYear { get; set; }
        public Nullable<int> UG_Marks { get; set; }
        public string UG_College { get; set; }
        public Nullable<int> UG_PassingYear { get; set; }
        public Nullable<int> Skill_1 { get; set; }
        public Nullable<int> Skill_2 { get; set; }
        public Nullable<int> Skill_3 { get; set; }
    
        public virtual User User { get; set; }
    }
}
