//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAdministrationSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Interview
    {
        public int InterviewID { get; set; }
        [Required(ErrorMessage ="Staff is required")]
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> UserId { get; set; }
        [Required(ErrorMessage = "Venue is required")]
        public string MettingId { get; set; }
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

        public string StatusId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<System.DateTime> InterviewTime { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual User User { get; set; }
    }
}
